language: python
python:
    - '3.4'
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - make
deploy:
  - provider: pypi
    distributions: sdist
    user: Remigascou
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.4"
    password:
      secure: ""
